=== brianhealey/jaffa-framework/jaffa-core/source/java/org/jaffa/security/domain/security-roles_1_0.dtd
<?xml version="1.0" encoding="US-ASCII"?>

<!ELEMENT roles (role*)>
<!ELEMENT role (description?, include*,exclude*,grant-function-access*) >
<!ATTLIST role name CDATA #REQUIRED >
<!ELEMENT include EMPTY>
<!ATTLIST include name CDATA #REQUIRED >
<!ELEMENT exclude EMPTY>
<!ATTLIST exclude name CDATA #REQUIRED >
<!ELEMENT grant-function-access EMPTY>
<!ATTLIST grant-function-access name CDATA #REQUIRED >
<!ELEMENT description (#PCDATA) >

=== brianhealey/jaffa-framework/jaffa-core/source/httpunittest/java/resources/httpunittest-roles.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE roles PUBLIC "-//JAFFA//DTD Security Roles 1.0//EN" "http://jaffa.sourceforge.net/DTD/security-roles_1_0.dtd">

<roles>
    <role name="CLERK">
        <description>This is a clerk</description>
    </role>
    <role name="SUPERVISOR">
        <grant-function-access name="Function1"/>
        <grant-function-access name="payroll.viewSalary"/>
        <grant-function-access name="payroll.transactionOverride"/>
    </role>
    <role name="MANAGER">
        <description>This is a Manager</description>
        <grant-function-access name="Function2"/>
        <grant-function-access name="payroll.updateSalary"/>
        <grant-function-access name="payroll.printWages"/>
    </role>
</roles>

=== brianhealey/jaffa-framework/jaffa-core/src/test/resources/resources/Roles.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE roles PUBLIC "-//JAFFA//DTD Security Roles 1.0//EN" "http://jaffa.sourceforge.net/DTD/security-roles_1_0.dtd">

<roles>
    <role name="CLERK">
        <description>This is a clerk</description>
        <grant-function-access name="FunctionAll"/>
    </role>
    <role name="SUPERVISOR">
        <grant-function-access name="Function1"/>
        <grant-function-access name="Function2"/>
        <grant-function-access name="FunctionA"/>
        <grant-function-access name="FunctionB"/>
        <grant-function-access name="FunctionAll"/>
    </role>
    <role name="MANAGER">
        <description>This is a Manager</description>
        <grant-function-access name="Function1"/>
        <grant-function-access name="Function2"/>
        <grant-function-access name="Function3"/>
        <grant-function-access name="FunctionA"/>
        <grant-function-access name="FunctionB"/>
        <grant-function-access name="FunctionC"/>
        <grant-function-access name="FunctionAll"/>
    </role>
</roles>

=== brianhealey/jaffa-framework/jaffa-components-user/source/test/junit/resources/roles.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE roles PUBLIC "-//JAFFA//DTD Security Roles 1.0//EN" "http://jaffa.sourceforge.net/DTD/security-roles_1_0.dtd">

<roles>
    <role name="TESTROLE1"/>
    <role name="TESTROLE2"/>
    <role name="TESTROLE3"/>
    <role name="DUMMYROLE1"/>
    
    <role name="CLERK">
        <description>This is a clerk</description>
    </role>
    
    <role name="SUPERVISOR">
        <grant-function-access name="Function1"/>
        <grant-function-access name="Function2"/>
        <grant-function-access name="FunctionA"/>
        <grant-function-access name="FunctionB"/>
    </role>
    
    <role name="MANAGER">
        <description>This is a Manager</description>
        <grant-function-access name="Function1"/>
        <grant-function-access name="Function2"/>
        <grant-function-access name="Function3"/>
        <grant-function-access name="FunctionA"/>
        <grant-function-access name="FunctionB"/>
        <grant-function-access name="FunctionC"/>
    </role>
</roles>
