=== brianhealey/jaffa-framework/jaffa-core/source/java/org/jaffa/persistence/engines/jdbcengine/configservice/jdbc-engine-mapping_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
This dtd is used for validating the mapping files used by the JDBC Engine.
It is in sync with the XML schema 'jdbc-engine-mapping_1_0.xsd' used for binding XML and Java.

Heres an example of a mapping file conforming to this DTD
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">
<classmap>
    <class name="org.jaffa.persistence.domainobjects.Asset">
        <map-to table="ZZ_JUT_ASSET" />

        <field name="AssetTk" use-member="m_assetTk" type="java.lang.Long" primary-key="true" autogen-key="true">
            <sql name="ASSET_TK" type="Integer" dirty="ignore"/>
        </field>

        <field name="AssetId" use-member="m_assetId" type="java.lang.String">
            <sql name="ASSET_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="Part" use-member="m_part" type="java.lang.String">
            <sql name="PART" type="STRING" dirty="ignore"/>
        </field>

        <field name="Custodian" use-member="m_custodian" type="java.lang.String">
            <sql name="CUSTODIAN" type="STRING" dirty="ignore"/>
        </field>

        <field name="Condition" use-member="m_condition" type="java.lang.String">
            <sql name="CONDITION" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedDatetime" use-member="m_createdDatetime" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_DATETIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="Qty" use-member="m_qty" type="java.lang.Long">
            <sql name="QTY" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="KeyRef" use-member="m_keyRef" type="java.lang.String">
            <sql name="KEY_REF" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>
-->
<!ELEMENT classmap (class)>

<!-- The domain class being mapped -->
<!ELEMENT class (map-to,field+)>
<!ATTLIST class name CDATA #REQUIRED>

<!-- The physical table in the database
    table: The name of the table in the database
    lockable: By default, the persistence engine will lock a table's row(s) before performing updates/deletes.
        However, it is quite possible that the table may actually be a complex view, which may not support the 'Select... FOR UPDATE NOWAIT' construct.
        For such cases, specify lockable='false' and put the appropriate locking code in the INSTEAD-OF triggers for the view.
-->
<!ELEMENT map-to EMPTY>
<!ATTLIST map-to table CDATA #REQUIRED>
<!ATTLIST map-to lockable (true|false) "true">

<!-- A field being mapped
  name: Name of the field
  type: The Java class being used for this field in the domain class
  use-member: By default, the persistence engine uses the getters/setters to obtain/set the value on a domain instance.
    The value for this attribute, if specified, should contain the field-name in the domain class to be used instead of getter/setter.
  primary-key: True, if this field is part of the primary-key
  autogen-key: True, if we want the database to generate the key
-->
<!ELEMENT field (sql)>
<!ATTLIST field
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    use-member CDATA #IMPLIED
    primary-key (true|false) "false"
    autogen-key (true|false) "false"
>

<!-- database specific attributes
    name: The name of the corresponding column in the database
    type: The datatype for the database column
    dirty: This attribute is not functional yet
    rpad: This is to support CHAR fields in the database, which suffer from the following peculiarities
      1- Pad the CHAR fields in the where clause of prepared-statements
      2- Pad the VARCHAR field or trim CHAR field when joining between VARCHAR and CHAR fields
      3- Trim the CHAR fields when using the Criteria.RELATIONAL_ENDS_WITH criteria
      4- Use "IS NULL OR = ' '" when checking for nulls
      5- Use "IS NOT NULL AND != ' '" when checking for not-nulls
-->
<!ELEMENT sql EMPTY>
<!ATTLIST sql
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    dirty CDATA "ignore"
    rpad CDATA #IMPLIED
>

=== brianhealey/jaffa-framework/jaffa-core/source/java/resources/jdbcengine/jaffa/FlexField.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.flexfields.domain.FlexField">
        <map-to table="J_FLEX_FIELDS" />

        <field name="FlexFieldId" use-member="m_flexFieldId" type="java.lang.String" primary-key="true">
            <sql name="FLEX_FIELD_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="ObjectName" use-member="m_objectName" type="java.lang.String">
            <sql name="OBJECT_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="Key1" use-member="m_key1" type="java.lang.String">
            <sql name="KEY1" type="STRING" dirty="ignore"/>
        </field>

        <field name="Key2" use-member="m_key2" type="java.lang.String">
            <sql name="KEY2" type="STRING" dirty="ignore"/>
        </field>

        <field name="Key3" use-member="m_key3" type="java.lang.String">
            <sql name="KEY3" type="STRING" dirty="ignore"/>
        </field>

        <field name="FieldName" use-member="m_fieldName" type="java.lang.String">
            <sql name="FIELD_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="Value" use-member="m_value" type="java.lang.String">
            <sql name="VALUE" type="STRING" dirty="ignore"/>
        </field>

        <field name="VersionNumber" use-member="m_versionNumber" type="java.lang.Long">
            <sql name="VERSION_NUMBER" type="INTEGER" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-components-user/source/java/jdbcengine/UserRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.applications.jaffa.modules.user.domain.UserRequest">
        <map-to table="USER_REQUEST" />

        <field name="RequestId" use-member="m_requestId" type="java.lang.Long" primary-key="true" autogen-key="true">
            <sql name="REQUEST_ID" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="UserName" use-member="m_userName" type="java.lang.String">
            <sql name="USER_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="FirstName" use-member="m_firstName" type="java.lang.String">
            <sql name="FIRST_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="LastName" use-member="m_lastName" type="java.lang.String">
            <sql name="LAST_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="Password" use-member="m_password" type="java.lang.String">
            <sql name="PASSWORD" type="STRING" dirty="ignore"/>
        </field>

        <field name="EMailAddress" use-member="m_eMailAddress" type="java.lang.String">
            <sql name="E_MAIL_ADDRESS" type="STRING" dirty="ignore"/>
        </field>

        <field name="SecurityQuestion" use-member="m_securityQuestion" type="java.lang.Long">
            <sql name="SECURITY_QUESTION" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="SecurityAnswer" use-member="m_securityAnswer" type="java.lang.String">
            <sql name="SECURITY_ANSWER" type="STRING" dirty="ignore"/>
        </field>

        <field name="Remarks" use-member="m_remarks" type="java.lang.String">
            <sql name="REMARKS" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedOn" use-member="m_createdOn" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_DATETIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="ProcessedDatetime" use-member="m_processedDatetime" type="org.jaffa.datatypes.DateTime">
            <sql name="PROCESSED_DATETIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="ProcessedUserId" use-member="m_processedUserId" type="java.lang.String">
            <sql name="PROCESSED_USER" type="STRING" dirty="ignore"/>
        </field>

        <field name="Status" use-member="m_status" type="java.lang.String">
            <sql name="STATUS" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-core/source/unittest/java/org/jaffa/persistence/mappingfiles/IPart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.persistence.domainobjects.IPart">
        <map-to table="ZZ_JUT_PART" />

        <field name="Part" type="java.lang.String" primary-key="true">
            <sql name="PART" type="STRING" dirty="ignore"/>
        </field>

        <field name="Noun" type="java.lang.String">
            <sql name="NOUN" type="STRING" dirty="ignore"/>
        </field>

        <field name="CategoryInstrument" type="java.lang.String">
            <sql name="CATEGORY_INSTRUMENT" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-console/source/java/resources/jdbcengine/jaffa/WSResultGraphRulesMetrics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.wsapi.domain.WSResultGraphRulesMetrics">
        <map-to table="J_WS_RULES_METRICS" />

        <field name="Id" use-member="m_id" type="java.lang.String" primary-key="true">
            <sql name="ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="WebServiceName" use-member="m_webServiceName" type="java.lang.String">
            <sql name="WEB_SERVICE_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="ResultGraphRules" use-member="m_resultGraphRules" type="java.lang.String">
            <sql name="RESULT_GRAPH_RULE" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedOn" use-member="m_createdOn" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-core/source/httpunittest/java/jdbcengine/UserTimeEntry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.applications.test.modules.time.domain.UserTimeEntry">
        <map-to table="UserTimeEntry" />

        <field name="UserName" use-member="m_userName" type="java.lang.String" primary-key="true">
            <sql name="USER_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="ProjectCode" use-member="m_projectCode" type="java.lang.String" primary-key="true">
            <sql name="PROJECT_CODE" type="STRING" dirty="ignore"/>
        </field>

        <field name="Activity" use-member="m_activity" type="java.lang.String">
            <sql name="ACTIVITY_CODE" type="STRING" dirty="ignore"/>
        </field>

        <field name="Task" use-member="m_task" type="java.lang.String" primary-key="true">
            <sql name="TASK_CODE" type="STRING" dirty="ignore"/>
        </field>

        <field name="PeriodStart" use-member="m_periodStart" type="org.jaffa.datatypes.DateTime" primary-key="true">
            <sql name="PERIOD_START" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="PeriodEnd" use-member="m_periodEnd" type="org.jaffa.datatypes.DateTime" primary-key="true">
            <sql name="PERIOD_END" type="DATE_TIME" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-core/source/unittest/java/org/jaffa/persistence/mappingfiles/IAsset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.persistence.domainobjects.IAsset">
        <map-to table="ZZ_JUT_ASSET" />

        <field name="AssetTk" type="java.lang.Long" primary-key="true" autogen-key="true">
            <sql name="ASSET_TK" type="Integer" dirty="ignore"/>
        </field>

        <field name="AssetId" type="java.lang.String">
            <sql name="ASSET_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="Part" type="java.lang.String">
            <sql name="PART" type="STRING" dirty="ignore"/>
        </field>

        <field name="Custodian" type="java.lang.String">
            <sql name="CUSTODIAN" type="STRING" dirty="ignore"/>
        </field>

        <field name="Condition" type="java.lang.String">
            <sql name="CONDITION" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedDatetime" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_DATETIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="Qty" type="java.lang.Long">
            <sql name="QTY" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="KeyRef" type="java.lang.String">
            <sql name="KEY_REF" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-core/source/java/resources/jdbcengine/jaffa/FlexFieldDelete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.flexfields.domain.FlexFieldDelete">
        <map-to table="J_FLEX_FIELDS_DEL" />

        <field name="FlexFieldId" use-member="m_flexFieldId" type="java.lang.String" primary-key="true">
            <sql name="FLEX_FIELD_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="ObjectName" use-member="m_objectName" type="java.lang.String">
            <sql name="OBJECT_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="Key1" use-member="m_key1" type="java.lang.String">
            <sql name="KEY1" type="STRING" dirty="ignore"/>
        </field>

        <field name="VersionNumber" use-member="m_versionNumber" type="java.lang.Long">
            <sql name="VERSION_NUMBER" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="DeletionCreatedOn" use-member="m_deletionCreatedOn" type="org.jaffa.datatypes.DateTime">
            <sql name="DELETION_CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-core/source/unittest/java/org/jaffa/persistence/mappingfiles/ICategoryOfInstrument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.persistence.domainobjects.ICategoryOfInstrument">
        <map-to table="ZZ_JUT_INSTRUMENT" />

        <field name="CategoryInstrument" type="java.lang.String" primary-key="true">
            <sql name="CATEGORY_INSTRUMENT" type="STRING" dirty="ignore"/>
        </field>

        <field name="Description" type="java.lang.String">
            <sql name="DESCRIPTION" type="STRING" dirty="ignore"/>
        </field>

        <field name="SupportEquip" type="java.lang.Boolean">
            <sql name="SUPPORT_EQUIP_B" type="BOOLEAN_BIT" dirty="ignore"/>
        </field>

        <field name="CalculateMtbf" type="java.lang.Boolean">
            <sql name="CALCULATE_MTBF_B" type="BOOLEAN_TF" dirty="ignore"/>
        </field>

    </class>
</classmap>
