=== brianhealey/jaffa-framework/jaffa-core/source/java/org/jaffa/persistence/engines/jdbcengine/configservice/jdbc-engine-mapping_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
This dtd is used for validating the mapping files used by the JDBC Engine.
It is in sync with the XML schema 'jdbc-engine-mapping_1_0.xsd' used for binding XML and Java.

Heres an example of a mapping file conforming to this DTD
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">
<classmap>
    <class name="org.jaffa.persistence.domainobjects.Asset">
        <map-to table="ZZ_JUT_ASSET" />

        <field name="AssetTk" use-member="m_assetTk" type="java.lang.Long" primary-key="true" autogen-key="true">
            <sql name="ASSET_TK" type="Integer" dirty="ignore"/>
        </field>

        <field name="AssetId" use-member="m_assetId" type="java.lang.String">
            <sql name="ASSET_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="Part" use-member="m_part" type="java.lang.String">
            <sql name="PART" type="STRING" dirty="ignore"/>
        </field>

        <field name="Custodian" use-member="m_custodian" type="java.lang.String">
            <sql name="CUSTODIAN" type="STRING" dirty="ignore"/>
        </field>

        <field name="Condition" use-member="m_condition" type="java.lang.String">
            <sql name="CONDITION" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedDatetime" use-member="m_createdDatetime" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_DATETIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="Qty" use-member="m_qty" type="java.lang.Long">
            <sql name="QTY" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="KeyRef" use-member="m_keyRef" type="java.lang.String">
            <sql name="KEY_REF" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>
-->
<!ELEMENT classmap (class)>

<!-- The domain class being mapped -->
<!ELEMENT class (map-to,field+)>
<!ATTLIST class name CDATA #REQUIRED>

<!-- The physical table in the database
    table: The name of the table in the database
    lockable: By default, the persistence engine will lock a table's row(s) before performing updates/deletes.
        However, it is quite possible that the table may actually be a complex view, which may not support the 'Select... FOR UPDATE NOWAIT' construct.
        For such cases, specify lockable='false' and put the appropriate locking code in the INSTEAD-OF triggers for the view.
-->
<!ELEMENT map-to EMPTY>
<!ATTLIST map-to table CDATA #REQUIRED>
<!ATTLIST map-to lockable (true|false) "true">

<!-- A field being mapped
  name: Name of the field
  type: The Java class being used for this field in the domain class
  use-member: By default, the persistence engine uses the getters/setters to obtain/set the value on a domain instance.
    The value for this attribute, if specified, should contain the field-name in the domain class to be used instead of getter/setter.
  primary-key: True, if this field is part of the primary-key
  autogen-key: True, if we want the database to generate the key
-->
<!ELEMENT field (sql)>
<!ATTLIST field
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    use-member CDATA #IMPLIED
    primary-key (true|false) "false"
    autogen-key (true|false) "false"
>

<!-- database specific attributes
    name: The name of the corresponding column in the database
    type: The datatype for the database column
    dirty: This attribute is not functional yet
    rpad: This is to support CHAR fields in the database, which suffer from the following peculiarities
      1- Pad the CHAR fields in the where clause of prepared-statements
      2- Pad the VARCHAR field or trim CHAR field when joining between VARCHAR and CHAR fields
      3- Trim the CHAR fields when using the Criteria.RELATIONAL_ENDS_WITH criteria
      4- Use "IS NULL OR = ' '" when checking for nulls
      5- Use "IS NOT NULL AND != ' '" when checking for not-nulls
-->
<!ELEMENT sql EMPTY>
<!ATTLIST sql
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    dirty CDATA "ignore"
    rpad CDATA #IMPLIED
>

=== brianhealey/jaffa-framework/jaffa-components-printing/source/java/resources/jdbcengine/jaffa/OutputCommand.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.modules.printing.domain.OutputCommand">
        <map-to table="J_OUTPUT_COMMANDS" />

        <field name="OutputCommandId" use-member="m_outputCommandId" type="java.lang.Long" primary-key="true" autogen-key="true">
            <sql name="OUTPUT_COMMAND_ID" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="OutputType" use-member="m_outputType" type="java.lang.String">
            <sql name="OUTPUT_TYPE" type="STRING" dirty="ignore"/>
        </field>

        <field name="SequenceNo" use-member="m_sequenceNo" type="java.lang.Long">
            <sql name="SEQUENCE_NO" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="OsPattern" use-member="m_osPattern" type="java.lang.String">
            <sql name="OS_PATTERN" type="STRING" dirty="ignore"/>
        </field>

        <field name="CommandLine" use-member="m_commandLine" type="java.lang.String">
            <sql name="COMMAND_LINE" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedOn" use-member="m_createdOn" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="CreatedBy" use-member="m_createdBy" type="java.lang.String">
            <sql name="CREATED_BY" type="STRING" dirty="ignore"/>
        </field>

        <field name="LastChangedOn" use-member="m_lastChangedOn" type="org.jaffa.datatypes.DateTime">
            <sql name="LAST_CHANGED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="LastChangedBy" use-member="m_lastChangedBy" type="java.lang.String">
            <sql name="LAST_CHANGED_BY" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-ria/source/java/resources/jdbcengine/jaffa/SavedQuery.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.ria.finder.domain.SavedQuery">
        <map-to table="J_SAVED_QUERIES" />

        <field name="QueryId" use-member="m_queryId" type="java.lang.String" primary-key="true">
            <sql name="QUERY_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="UserId" use-member="m_userId" type="java.lang.String">
            <sql name="USER_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="ComponentRef" use-member="m_componentRef" type="java.lang.String">
            <sql name="COMPONENT_REF" type="STRING" dirty="ignore"/>
        </field>

        <field name="ContextRef" use-member="m_contextRef" type="java.lang.String">
            <sql name="CONTEXT_REF" type="STRING" dirty="ignore"/>
        </field>

        <field name="QueryName" use-member="m_queryName" type="java.lang.String">
            <sql name="QUERY_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="IsDefault" use-member="m_isDefault" type="java.lang.Boolean">
            <sql name="IS_DEFAULT" type="BOOLEAN" dirty="ignore"/>
        </field>

        <field name="Criteria" use-member="m_criteria" type="java.lang.String">
            <sql name="CRITERIA" type="CLOB" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-components-printing/source/java/resources/jdbcengine/jaffa/FormDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.modules.printing.domain.FormDefinition">
        <map-to table="J_FORM_DEFINITIONS" />

        <field name="FormId" use-member="m_formId" type="java.lang.Long" primary-key="true" autogen-key="true">
            <sql name="FORM_ID" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="FormName" use-member="m_formName" type="java.lang.String">
            <sql name="FORM_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="FormAlternate" use-member="m_formAlternate" type="java.lang.String">
            <sql name="FORM_ALTERNATE" type="STRING" dirty="ignore"/>
        </field>

        <field name="FormVariation" use-member="m_formVariation" type="java.lang.String">
            <sql name="FORM_VARIATION" type="STRING" dirty="ignore"/>
        </field>

        <field name="OutputType" use-member="m_outputType" type="java.lang.String">
            <sql name="OUTPUT_TYPE" type="STRING" dirty="ignore"/>
        </field>

        <field name="FormTemplate" use-member="m_formTemplate" type="java.lang.String">
            <sql name="FORM_TEMPLATE" type="STRING" dirty="ignore"/>
        </field>

        <field name="FieldLayout" use-member="m_fieldLayout" type="java.lang.String">
            <sql name="FIELD_LAYOUT" type="STRING" dirty="ignore"/>
        </field>

        <field name="Description" use-member="m_description" type="java.lang.String">
            <sql name="DESCRIPTION" type="STRING" dirty="ignore"/>
        </field>

        <field name="Remarks" use-member="m_remarks" type="java.lang.String">
            <sql name="REMARKS" type="STRING" dirty="ignore"/>
        </field>

        <field name="DomFactory" use-member="m_domFactory" type="java.lang.String">
            <sql name="DOM_FACTORY" type="STRING" dirty="ignore"/>
        </field>

        <field name="DomClass" use-member="m_domClass" type="java.lang.String">
            <sql name="DOM_CLASS" type="STRING" dirty="ignore"/>
        </field>

        <field name="DomKey1" use-member="m_domKey1" type="java.lang.String">
            <sql name="DOM_KEY1" type="STRING" dirty="ignore"/>
        </field>

        <field name="DomKey2" use-member="m_domKey2" type="java.lang.String">
            <sql name="DOM_KEY2" type="STRING" dirty="ignore"/>
        </field>

        <field name="DomKey3" use-member="m_domKey3" type="java.lang.String">
            <sql name="DOM_KEY3" type="STRING" dirty="ignore"/>
        </field>

        <field name="DomKey4" use-member="m_domKey4" type="java.lang.String">
            <sql name="DOM_KEY4" type="STRING" dirty="ignore"/>
        </field>

        <field name="DomKey5" use-member="m_domKey5" type="java.lang.String">
            <sql name="DOM_KEY5" type="STRING" dirty="ignore"/>
        </field>

        <field name="DomKey6" use-member="m_domKey6" type="java.lang.String">
            <sql name="DOM_KEY6" type="STRING" dirty="ignore"/>
        </field>

        <field name="AdditionalDataComponent" use-member="m_additionalDataComponent" type="java.lang.String">
            <sql name="ADDITIONAL_DATA_COMPONENT" type="STRING" dirty="ignore"/>
        </field>

        <field name="FollowOnFormName" use-member="m_followOnFormName" type="java.lang.String">
            <sql name="FOLLOW_ON_FORM_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="FollowOnFormAlternate" use-member="m_followOnFormAlternate" type="java.lang.String">
            <sql name="FOLLOW_ON_FORM_ALTERNATE" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedOn" use-member="m_createdOn" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="CreatedBy" use-member="m_createdBy" type="java.lang.String">
            <sql name="CREATED_BY" type="STRING" dirty="ignore"/>
        </field>

        <field name="LastChangedOn" use-member="m_lastChangedOn" type="org.jaffa.datatypes.DateTime">
            <sql name="LAST_CHANGED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="LastChangedBy" use-member="m_lastChangedBy" type="java.lang.String">
            <sql name="LAST_CHANGED_BY" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-core/source/unittest/java/org/jaffa/persistence/mappingfiles/Asset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.persistence.domainobjects.Asset">
        <map-to table="ZZ_JUT_ASSET" />

        <field name="AssetTk" use-member="m_assetTk" type="java.lang.Long" primary-key="true" autogen-key="true">
            <sql name="ASSET_TK" type="Integer" dirty="ignore"/>
        </field>

        <field name="AssetId" use-member="m_assetId" type="java.lang.String">
            <sql name="ASSET_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="Part" use-member="m_part" type="java.lang.String">
            <sql name="PART" type="STRING" dirty="ignore"/>
        </field>

        <field name="Custodian" use-member="m_custodian" type="java.lang.String">
            <sql name="CUSTODIAN" type="STRING" dirty="ignore"/>
        </field>

        <field name="Condition" use-member="m_condition" type="java.lang.String">
            <sql name="CONDITION" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedDatetime" use-member="m_createdDatetime" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_DATETIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="Qty" use-member="m_qty" type="java.lang.Long">
            <sql name="QTY" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="KeyRef" use-member="m_keyRef" type="java.lang.String">
            <sql name="KEY_REF" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-soa/source/java/resources/jdbcengine/jaffa/TransactionPayload.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.transaction.domain.TransactionPayload">
        <map-to table="J_TRANSACTION_PAYLOADS" lockable="false"/>

        <field name="Id" use-member="m_id" type="java.lang.String" primary-key="true">
            <sql name="ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="ExternalMessage" use-member="m_externalMessage" type="byte[]">
            <sql name="EXTERNAL_MESSAGE" type="BLOB" dirty="ignore"/>
        </field>

        <field name="InternalMessage" use-member="m_internalMessage" type="byte[]">
            <sql name="INTERNAL_MESSAGE" type="BLOB" dirty="ignore"/>
        </field>

        <field name="InternalMessageClass" use-member="m_internalMessageClass" type="java.lang.String">
            <sql name="INTERNAL_MESSAGE_CLASS" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-components/source/java/resources/jdbcengine/jaffa/Attachment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.components.attachment.domain.Attachment">
        <map-to table="J_ATTACHMENTS" />

        <field name="AttachmentId" use-member="m_attachmentId" type="java.lang.String" primary-key="true">
            <sql name="ATTACHMENT_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="DocumentReferenceId" use-member="m_documentReferenceId" type="java.lang.String">
            <sql name="DOCUMENT_REFERENCE_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="SerializedKey" use-member="m_serializedKey" type="java.lang.String">
            <sql name="SERIALIZED_KEY" type="STRING" dirty="ignore"/>
        </field>

        <field name="OriginalFileName" use-member="m_originalFileName" type="java.lang.String">
            <sql name="ORIGINAL_FILE_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="AttachmentType" use-member="m_attachmentType" type="java.lang.String">
            <sql name="ATTACHMENT_TYPE" type="STRING" dirty="ignore"/>
        </field>

        <field name="ContentType" use-member="m_contentType" type="java.lang.String">
            <sql name="CONTENT_TYPE" type="STRING" dirty="ignore"/>
        </field>

        <field name="Description" use-member="m_description" type="java.lang.String">
            <sql name="DESCRIPTION" type="STRING" dirty="ignore"/>
        </field>

        <field name="Remarks" use-member="m_remarks" type="java.lang.String">
            <sql name="REMARKS" type="STRING" dirty="ignore"/>
        </field>

        <field name="SupercededBy" use-member="m_supercededBy" type="java.lang.String">
            <sql name="SUPERCEDED_BY" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedOn" use-member="m_createdOn" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="CreatedBy" use-member="m_createdBy" type="java.lang.String">
            <sql name="CREATED_BY" type="STRING" dirty="ignore"/>
        </field>

        <field name="LastChangedOn" use-member="m_lastChangedOn" type="org.jaffa.datatypes.DateTime">
            <sql name="LAST_CHANGED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="LastChangedBy" use-member="m_lastChangedBy" type="java.lang.String">
            <sql name="LAST_CHANGED_BY" type="STRING" dirty="ignore"/>
        </field>

        <field name="VersionNumber" use-member="m_versionNumber" type="java.lang.Long">
            <sql name="VERSION_NUMBER" type="INTEGER" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-components-printing/source/java/resources/jdbcengine/jaffa/FormUsage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.modules.printing.domain.FormUsage">
        <map-to table="J_FORM_USAGES" />

        <field name="FormName" use-member="m_formName" type="java.lang.String" primary-key="true">
            <sql name="FORM_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="EventName" use-member="m_eventName" type="java.lang.String" primary-key="true">
            <sql name="EVENT_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="FormAlternate" use-member="m_formAlternate" type="java.lang.String">
            <sql name="FORM_ALTERNATE" type="STRING" dirty="ignore"/>
        </field>

        <field name="Copies" use-member="m_copies" type="java.lang.Long">
            <sql name="COPIES" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="CreatedOn" use-member="m_createdOn" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="CreatedBy" use-member="m_createdBy" type="java.lang.String">
            <sql name="CREATED_BY" type="STRING" dirty="ignore"/>
        </field>

        <field name="LastChangedOn" use-member="m_lastChangedOn" type="org.jaffa.datatypes.DateTime">
            <sql name="LAST_CHANGED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="LastChangedBy" use-member="m_lastChangedBy" type="java.lang.String">
            <sql name="LAST_CHANGED_BY" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-core/source/unittest/java/org/jaffa/persistence/mappingfiles/PartPicture.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.persistence.domainobjects.PartPicture">
        <map-to table="ZZ_JUT_PART_PIC" />

        <field name="Part" use-member="m_part" type="java.lang.String" primary-key="true">
            <sql name="PART" type="STRING" dirty="ignore"/>
        </field>

        <field name="SmallPicture" use-member="m_smallPicture" type="byte[]">
            <sql name="SMALL_PICTURE" type="RAW" dirty="ignore"/>
        </field>

        <field name="Picture" use-member="m_picture" type="byte[]">
            <sql name="PICTURE" type="LONGRAW" dirty="ignore"/>
        </field>

    </class>
</classmap>
