=== brianhealey/jaffa-framework/jaffa-core/source/java/org/jaffa/persistence/engines/jdbcengine/configservice/jdbc-engine-mapping_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
This dtd is used for validating the mapping files used by the JDBC Engine.
It is in sync with the XML schema 'jdbc-engine-mapping_1_0.xsd' used for binding XML and Java.

Heres an example of a mapping file conforming to this DTD
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">
<classmap>
    <class name="org.jaffa.persistence.domainobjects.Asset">
        <map-to table="ZZ_JUT_ASSET" />

        <field name="AssetTk" use-member="m_assetTk" type="java.lang.Long" primary-key="true" autogen-key="true">
            <sql name="ASSET_TK" type="Integer" dirty="ignore"/>
        </field>

        <field name="AssetId" use-member="m_assetId" type="java.lang.String">
            <sql name="ASSET_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="Part" use-member="m_part" type="java.lang.String">
            <sql name="PART" type="STRING" dirty="ignore"/>
        </field>

        <field name="Custodian" use-member="m_custodian" type="java.lang.String">
            <sql name="CUSTODIAN" type="STRING" dirty="ignore"/>
        </field>

        <field name="Condition" use-member="m_condition" type="java.lang.String">
            <sql name="CONDITION" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedDatetime" use-member="m_createdDatetime" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_DATETIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="Qty" use-member="m_qty" type="java.lang.Long">
            <sql name="QTY" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="KeyRef" use-member="m_keyRef" type="java.lang.String">
            <sql name="KEY_REF" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>
-->
<!ELEMENT classmap (class)>

<!-- The domain class being mapped -->
<!ELEMENT class (map-to,field+)>
<!ATTLIST class name CDATA #REQUIRED>

<!-- The physical table in the database
    table: The name of the table in the database
    lockable: By default, the persistence engine will lock a table's row(s) before performing updates/deletes.
        However, it is quite possible that the table may actually be a complex view, which may not support the 'Select... FOR UPDATE NOWAIT' construct.
        For such cases, specify lockable='false' and put the appropriate locking code in the INSTEAD-OF triggers for the view.
-->
<!ELEMENT map-to EMPTY>
<!ATTLIST map-to table CDATA #REQUIRED>
<!ATTLIST map-to lockable (true|false) "true">

<!-- A field being mapped
  name: Name of the field
  type: The Java class being used for this field in the domain class
  use-member: By default, the persistence engine uses the getters/setters to obtain/set the value on a domain instance.
    The value for this attribute, if specified, should contain the field-name in the domain class to be used instead of getter/setter.
  primary-key: True, if this field is part of the primary-key
  autogen-key: True, if we want the database to generate the key
-->
<!ELEMENT field (sql)>
<!ATTLIST field
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    use-member CDATA #IMPLIED
    primary-key (true|false) "false"
    autogen-key (true|false) "false"
>

<!-- database specific attributes
    name: The name of the corresponding column in the database
    type: The datatype for the database column
    dirty: This attribute is not functional yet
    rpad: This is to support CHAR fields in the database, which suffer from the following peculiarities
      1- Pad the CHAR fields in the where clause of prepared-statements
      2- Pad the VARCHAR field or trim CHAR field when joining between VARCHAR and CHAR fields
      3- Trim the CHAR fields when using the Criteria.RELATIONAL_ENDS_WITH criteria
      4- Use "IS NULL OR = ' '" when checking for nulls
      5- Use "IS NOT NULL AND != ' '" when checking for not-nulls
-->
<!ELEMENT sql EMPTY>
<!ATTLIST sql
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    dirty CDATA "ignore"
    rpad CDATA #IMPLIED
>

=== brianhealey/jaffa-framework/jaffa-components/source/java/resources/jdbcengine/jaffa/AuditTransactionView.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.components.audit.domain.AuditTransactionView">
        <map-to table="J_AUDIT_TRANSACTIONS$VIEW" />

        <field name="TransactionId" use-member="m_transactionId" type="java.lang.String">
            <sql name="TRANSACTION_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="ProcessName" use-member="m_processName" type="java.lang.String">
            <sql name="PROCESS_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="SubProcessName" use-member="m_subProcessName" type="java.lang.String">
            <sql name="SUB_PROCESS_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="Reason" use-member="m_reason" type="java.lang.String">
            <sql name="REASON" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedBy" use-member="m_createdBy" type="java.lang.String">
            <sql name="CREATED_BY" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedOn" use-member="m_createdOn" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="ObjectId" use-member="m_objectId" type="java.lang.String">
            <sql name="OBJECT_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="ObjectName" use-member="m_objectName" type="java.lang.String">
            <sql name="OBJECT_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="ChangeType" use-member="m_changeType" type="java.lang.String">
            <sql name="CHANGE_TYPE" type="STRING" dirty="ignore"/>
        </field>

        <field name="FieldId" use-member="m_fieldId" type="java.lang.String">
            <sql name="FIELD_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="FieldName" use-member="m_fieldName" type="java.lang.String">
            <sql name="FIELD_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="FromValue" use-member="m_fromValue" type="java.lang.String">
            <sql name="FROM_VALUE" type="STRING" dirty="ignore"/>
        </field>

        <field name="ToValue" use-member="m_toValue" type="java.lang.String">
            <sql name="TO_VALUE" type="STRING" dirty="ignore"/>
        </field>

        <field name="Changed" use-member="m_changed" type="java.lang.Boolean">
            <sql name="CHANGED" type="BOOLEAN" dirty="ignore"/>
        </field>

        <field name="Flex" use-member="m_flex" type="java.lang.Boolean">
            <sql name="FLEX" type="BOOLEAN" dirty="ignore"/>
        </field>

        <field name="OverflowFlag" use-member="m_overflowFlag" type="java.lang.Boolean">
            <sql name="OVERFLOW_FLAG" type="BOOLEAN" dirty="ignore"/>
        </field>

        <field name="MultilineHtmlFlag" use-member="m_multilineHtmlFlag" type="java.lang.String">
            <sql name="MULTILINE_HTML_FLAG" type="STRING" dirty="ignore"/>
        </field>

        <field name="PK" use-member="m_pK" type="java.lang.String" primary-key="true">
            <sql name="PK" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-components/source/java/resources/jdbcengine/jaffa/AttachmentDelete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.components.attachment.domain.AttachmentDelete">
        <map-to table="J_ATTACHMENTS_DEL" />

        <field name="AttachmentId" use-member="m_attachmentId" type="java.lang.String" primary-key="true">
            <sql name="ATTACHMENT_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="SerializedKey" use-member="m_serializedKey" type="java.lang.String">
            <sql name="SERIALIZED_KEY" type="STRING" dirty="ignore"/>
        </field>

        <field name="VersionNumber" use-member="m_versionNumber" type="java.lang.Long">
            <sql name="VERSION_NUMBER" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="DeletionCreatedOn" use-member="m_deletionCreatedOn" type="org.jaffa.datatypes.DateTime">
            <sql name="DELETION_CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-soa/source/java/resources/jdbcengine/jaffa/TransactionField.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.transaction.domain.TransactionField">
        <map-to table="J_TRANSACTION_FIELDS" lockable="false"/>

        <field name="TransactionId" use-member="m_transactionId" type="java.lang.String" primary-key="true">
            <sql name="TRANSACTION_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="FieldName" use-member="m_fieldName" type="java.lang.String" primary-key="true">
            <sql name="FIELD_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="Value" use-member="m_value" type="java.lang.String">
            <sql name="VALUE" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-core/source/unittest/java/org/jaffa/persistence/mappingfiles/IPartRemarksPicture.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.persistence.domainobjects.IPartRemarksPicture">
        <map-to table="ZZ_JUT_PART_REM_PIC" />

        <field name="Part" type="java.lang.String" primary-key="true">
            <sql name="PART" type="STRING" dirty="ignore"/>
        </field>

        <field name="Remarks" type="java.lang.String">
            <sql name="REMARKS" type="CLOB" dirty="ignore"/>
        </field>

        <field name="Picture" type="byte[]">
            <sql name="PICTURE" type="BLOB" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-components/source/java/resources/jdbcengine/jaffa/AuditTransactionField.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.components.audit.domain.AuditTransactionField">
        <map-to table="J_AUDIT_TRANSACTION_FIELDS" />

        <field name="FieldId" use-member="m_fieldId" type="java.lang.String" primary-key="true">
            <sql name="FIELD_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="ObjectId" use-member="m_objectId" type="java.lang.String">
            <sql name="OBJECT_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="FieldName" use-member="m_fieldName" type="java.lang.String">
            <sql name="FIELD_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="FromValue" use-member="m_fromValue" type="java.lang.String">
            <sql name="FROM_VALUE" type="STRING" dirty="ignore"/>
        </field>

        <field name="ToValue" use-member="m_toValue" type="java.lang.String">
            <sql name="TO_VALUE" type="STRING" dirty="ignore"/>
        </field>

        <field name="Changed" use-member="m_changed" type="java.lang.Boolean">
            <sql name="CHANGED" type="BOOLEAN" dirty="ignore"/>
        </field>

        <field name="Flex" use-member="m_flex" type="java.lang.Boolean">
            <sql name="FLEX" type="BOOLEAN" dirty="ignore"/>
        </field>

        <field name="OverflowFlag" use-member="m_overflowFlag" type="java.lang.Boolean">
            <sql name="OVERFLOW_FLAG" type="BOOLEAN" dirty="ignore"/>
        </field>

        <field name="MultilineHtmlFlag" use-member="m_multilineHtmlFlag" type="java.lang.String">
            <sql name="MULTILINE_HTML_FLAG" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-components-printing/source/java/resources/jdbcengine/jaffa/FormEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.modules.printing.domain.FormEvent">
        <map-to table="J_FORM_EVENTS" />

        <field name="EventName" use-member="m_eventName" type="java.lang.String" primary-key="true">
            <sql name="EVENT_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="Description" use-member="m_description" type="java.lang.String">
            <sql name="DESCRIPTION" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedOn" use-member="m_createdOn" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="CreatedBy" use-member="m_createdBy" type="java.lang.String">
            <sql name="CREATED_BY" type="STRING" dirty="ignore"/>
        </field>

        <field name="LastChangedOn" use-member="m_lastChangedOn" type="org.jaffa.datatypes.DateTime">
            <sql name="LAST_CHANGED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="LastChangedBy" use-member="m_lastChangedBy" type="java.lang.String">
            <sql name="LAST_CHANGED_BY" type="STRING" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-console/source/java/resources/jdbcengine/jaffa/WebServiceMetrics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.wsapi.domain.WebServiceMetrics">
        <map-to table="J_WEBSERVICE_METRICS" />

        <field name="Id" use-member="m_id" type="java.lang.String" primary-key="true">
            <sql name="ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="EndpointName" use-member="m_endpointName" type="java.lang.String">
            <sql name="ENDPOINT_NAME" type="STRING" dirty="ignore"/>
        </field>

        <field name="EndpointAddress" use-member="m_endpointAddress" type="java.lang.String">
            <sql name="ENDPOINT_ADDRESS" type="STRING" dirty="ignore"/>
        </field>

        <field name="IPAddress" use-member="m_iPAddress" type="java.lang.String">
            <sql name="IP_ADDRESS" type="STRING" dirty="ignore"/>
        </field>

        <field name="Port" use-member="m_port" type="java.lang.String">
            <sql name="PORT" type="STRING" dirty="ignore"/>
        </field>

        <field name="StartTime" use-member="m_startTime" type="org.jaffa.datatypes.DateTime">
            <sql name="START_TIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="StopTime" use-member="m_stopTime" type="org.jaffa.datatypes.DateTime">
            <sql name="STOP_TIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="RequestCount" use-member="m_requestCount" type="java.lang.Long">
            <sql name="REQUEST_COUNT" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="ResponseCount" use-member="m_responseCount" type="java.lang.Long">
            <sql name="RESPONSE_COUNT" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="FaultCount" use-member="m_faultCount" type="java.lang.Long">
            <sql name="FAULT_COUNT" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="MinProcessingTime" use-member="m_minProcessingTime" type="java.lang.String">
            <sql name="MIN_PROCESSING_TIME" type="STRING" dirty="ignore"/>
        </field>

        <field name="MaxProcessingTime" use-member="m_maxProcessingTime" type="java.lang.String">
            <sql name="MAX_PROCESSING_TIME" type="STRING" dirty="ignore"/>
        </field>

        <field name="AvgProcessingTime" use-member="m_avgProcessingTime" type="java.lang.String">
            <sql name="AVG_PROCESSING_TIME" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedOn" use-member="m_createdOn" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_ON" type="DATE_TIME" dirty="ignore"/>
        </field>

    </class>
</classmap>

=== brianhealey/jaffa-framework/jaffa-core/source/unittest/java/org/jaffa/persistence/mappingfiles/IItem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classmap PUBLIC "-//JAFFA//DTD JDBC Engine Mapping 1.0//EN" "http://jaffa.sourceforge.net/DTD/jdbc-engine-mapping_1_0.dtd">

<classmap>
    <class name="org.jaffa.persistence.domainobjects.IItem">
        <map-to table="ZZ_JUT_ITEM" />

        <field name="ItemId" type="java.lang.String" primary-key="true">
            <sql name="ITEM_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="ReceivedItemId" type="java.lang.String">
            <sql name="RECEIVED_ITEM_ID" type="STRING" dirty="ignore"/>
        </field>

        <field name="Part" type="java.lang.String">
            <sql name="PART" type="STRING" dirty="ignore"/>
        </field>

        <field name="Prime" type="java.lang.String">
            <sql name="PRIME" type="STRING" dirty="ignore"/>
        </field>

        <field name="Sc" type="java.lang.String">
            <sql name="SC" type="STRING" dirty="ignore"/>
        </field>

        <field name="Condition" type="java.lang.String">
            <sql name="CONDITION" type="STRING" dirty="ignore"/>
        </field>

        <field name="CreatedDatetime" type="org.jaffa.datatypes.DateTime">
            <sql name="CREATED_DATETIME" type="DATE_TIME" dirty="ignore"/>
        </field>

        <field name="Qty" type="java.lang.Long">
            <sql name="QTY" type="INTEGER" dirty="ignore"/>
        </field>

        <field name="KeyRef" type="java.lang.String">
            <sql name="KEY_REF" type="STRING" dirty="ignore"/>
        </field>

        <field name="Status1" type="java.lang.String">
            <sql name="STATUS_1" type="STRING" dirty="ignore"/>
        </field>

        <field name="Status2" type="java.lang.String">
            <sql name="STATUS_2" type="STRING" dirty="ignore"/>
        </field>

        <field name="Status3" type="java.lang.String">
            <sql name="STATUS_3" type="STRING" dirty="ignore"/>
        </field>

        <field name="Price" type="java.lang.Double">
            <sql name="PRICE" type="DECIMAL" dirty="ignore"/>
        </field>

    </class>
</classmap>
