=== brianhealey/jaffa-framework/jaffa-core/source/java/org/jaffa/rules/metadata/rules_1_0.dtd
<?xml version="1.0" encoding="US-ASCII"?>

<!-- This dtd is used for validating the input xml to the RulesMetaDataService -->

<!ELEMENT rules (domain*,dto*)>
<!ELEMENT domain (field*)>
<!ATTLIST domain class CDATA #REQUIRED>
<!ELEMENT dto (field*)>
<!ATTLIST dto class CDATA #REQUIRED>

<!-- The new validators should be added to the field element -->
<!ELEMENT field ((mandatory|foreign-key|generic-foreign-key|in-list|string|boolean|currency|dateonly|datetime|decimal|integer)*)>
<!ATTLIST field name CDATA #REQUIRED>

<!-- This attribute can have true/false values. It has an impact only in a variant file.
By default, the value will be false, and hence the variant file will be treated as extending the rules in the core file.
However, if the value is true, then the core-rules will not be invoked.
-->
<!ATTLIST field overridesDefault (true|false) "false">

<!-- The following 2 attributesUse will be used to inherit the rules from another field. Both the values should be supplied, if inheritance is desired -->
<!ATTLIST field extendsClass CDATA #IMPLIED>
<!ATTLIST field extendsField CDATA #IMPLIED>



<!-- The different field validators -->
<!ELEMENT mandatory EMPTY>

<!ELEMENT foreign-key EMPTY>
<!ATTLIST foreign-key domainClass CDATA #REQUIRED property CDATA #REQUIRED>

<!ELEMENT generic-foreign-key EMPTY>
<!ATTLIST generic-foreign-key tableName CDATA #REQUIRED fieldName CDATA #REQUIRED>

<!ELEMENT in-list EMPTY>
<!ATTLIST in-list list CDATA #REQUIRED separator CDATA ",">

<!ELEMENT string EMPTY>
<!ATTLIST string pattern CDATA #IMPLIED length CDATA #IMPLIED minLength CDATA #IMPLIED caseType (UpperCase|LowerCase|MixedCase) "MixedCase">

<!ELEMENT boolean EMPTY>
<!ATTLIST boolean pattern CDATA #IMPLIED>

<!ELEMENT currency EMPTY>
<!ATTLIST currency layout CDATA #IMPLIED minValue CDATA #IMPLIED maxValue CDATA #IMPLIED intSize CDATA #IMPLIED fracSize CDATA #IMPLIED>

<!ELEMENT dateonly EMPTY>
<!ATTLIST dateonly layout CDATA #IMPLIED minValue CDATA #IMPLIED maxValue CDATA #IMPLIED>

<!ELEMENT datetime EMPTY>
<!ATTLIST datetime layout CDATA #IMPLIED minValue CDATA #IMPLIED maxValue CDATA #IMPLIED>

<!ELEMENT decimal EMPTY>
<!ATTLIST decimal layout CDATA #IMPLIED minValue CDATA #IMPLIED maxValue CDATA #IMPLIED intSize CDATA #IMPLIED fracSize CDATA #IMPLIED>

<!ELEMENT integer EMPTY>
<!ATTLIST integer layout CDATA #IMPLIED minValue CDATA #IMPLIED maxValue CDATA #IMPLIED intSize CDATA #IMPLIED>

=== brianhealey/jaffa-framework/jaffa-core/source/unittest/java/resources/core-rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rules PUBLIC "-//JAFFA//DTD Dynamic Rules 1.0//EN" "http://jaffa.sourceforge.net/DTD/rules_1_0.dtd">

<rules>
    <domain class="org.jaffa.persistence.domainobjects.Item">
    
        <!-- Enforce the mandatory check -->
        <field name="ItemId">
            <mandatory/>
        </field>
        
        <!-- The value should be a valid key on the zz_jut_condition table -->
        <field name="Condition">
            <foreign-key domainClass="org.jaffa.persistence.domainobjects.Condition" property="Condition"/>
        </field>
        
        <!-- Limit the values to X,S,A,Y,T,B,1,2 -->
        <field name="Status1">
            <generic-foreign-key tableName="ZZ_JUT_ITEM" fieldName="STATUS"/>
        </field>
        
        <!-- Limit the values to X,S,A,Y,T,B,1,2 -->
        <field name="Status2" extendsClass="org.jaffa.persistence.domainobjects.Item" extendsField="Status1"/>
        
        <!-- Limit the values to P,Q,R -->
        <field name="Status3">
            <in-list list="P;Q;R" separator=";"/>
        </field>
        
    </domain>

    <!-- The following class is used for merely testing the various types of field-validators -->
    <domain class="Dummy">
        <field name="StringField"><string length="5" caseType="UpperCase" pattern="(ABCDE)|(PQRSTU)|(ABC)"/></field>
        <field name="BooleanField"><boolean pattern="(true|yes|1)|(false|no|0)"/></field>
        <field name="CurrencyField"><currency minValue="100" maxValue="5000" intSize="4" fracSize="2"/></field>
        <field name="DateOnlyField"><dateonly minValue="1/1/2000" maxValue="1/1/2010"/></field>
        <field name="DateTimeField"><datetime minValue="1/1/2000" maxValue="1/1/2010"/></field>
        <field name="DecimalField"><decimal minValue="100" maxValue="5000" intSize="4" fracSize="2"/></field>
        <field name="IntegerField"><integer minValue="100" maxValue="5000" intSize="4"/></field>
    </domain>
</rules>
